apiVersion: apps/v1
kind: Deployment
metadata:
  name: bgd
spec:
  template:
    metadata:
    spec:
      containers:
      - image: quay.io/redhatworkshops/bgd:latest
        name: bgd
        env:
        - name: COLOR
          value: "green"