apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: bgd
spec:
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
        - name: COLOR
          value: "green"