apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: bgd
  name: bgd
spec:
  template:
    metadata:
    spec:
      containers:
      - name: bgd
        env:
        - name: COLOR
          value: "green"