apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world 
  labels:
    app: helloWorld
spec:
  replicas: 1
  selector:
    matchLabels:
      app: helloWorld
  template:
    metadata:
      labels:
        app: helloWorld
    spec:
      containers:
      - name: helloWorld
        image: quay.io/openshifttest/hello-openshift
        ports:
        - containerPort: 8080