apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-bgd
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/cronchiq/argocd.git
    targetRevision: main
    path: kustomize-bgd/overlays/dev

  destination:
    server: https://api.njzmp.okd.cz.o2:6443
    namespace: dev-bgd

 
